export interface Movie {
    imdbid: string,
    title: string,
    year: string,
    rated: string,
    released: Date,
    runtime: string,
    genre: string,
    director: string,
    writer:string,
    actors: string,
    plot: string,
    boxoffice: string,
    language: string,
    country: string,
    awards: string,
    poster: string,
    metascore: string,
    imdbrating: string,
    imdbvotes: string,
    type: string,
    dvd: Date,
    production: string,
    website: string,
    response: boolean,
    totalseasons: number
}
